sudo: required
dist: trusty
language: PHP
php: 7.1
install: composer install

before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - ./vendor/laravel/dusk/bin/chromedriver-linux &
    - cp .env.testing .env
    - php artisan serve > /dev/null 2>&1 &

script:
    - touch database/database.sqlite
    - php artisan migrate
    - phpunit
    - php artisan dusk

